name: Deploy Job

on:
  push:
    branches:
      - feature/change1   # Trigger on push to dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your S3 bucket region

    - name: Upload index.html to S3
      run: |
        aws s3 cp index.html s3://studenthtmlbucket/
        echo "✅ File uploaded to S3."

    - name: Wait for 3 minutes before next job
      run: |
        echo "⏳ Waiting for 3 minutes..."
        sleep 60
        echo "✅ Done waiting, continuing..."
